apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wp-autoscale
  namespace: mywordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
